package com.ulas.springcoretemplate.constant;


import lombok.Getter;
import org.springframework.http.HttpStatus;

import static org.springframework.http.HttpStatus.BAD_REQUEST;
import static org.springframework.http.HttpStatus.UNAUTHORIZED;

@Getter
public enum ErrorConstants {
    UN_AUTHORIZED(UNAUTHORIZED, "0021"),
    FORBIDDEN(HttpStatus.FORBIDDEN, "0021"),
    NULL_FILE(BAD_REQUEST, "0049"),
    IMAGE_WIDTH_TO_HEIGHT_RATIO_UNACCEPTABLE(BAD_REQUEST, "0050"),
    TIME_COULD_NOT_CREATED(BAD_REQUEST, "0051"),
    INVALID_ID(BAD_REQUEST, "0003"),
    USER_NOT_EXIST(BAD_REQUEST, "0002"),
    MULTIPLE_LOGIN_FAILURE(BAD_REQUEST, "0037"),
    NUMBER_OF_REGISTER_REQUEST_EXCEEDED(BAD_REQUEST, "0036"),
    NUMBER_OF_SMS_REQUEST_EXCEEDED(BAD_REQUEST, "0035"),
    INVALID_TOKEN(BAD_REQUEST, "0052"),
    INVALID_OPERATION(BAD_REQUEST, "0004"),
    PHONE_NUMBER_IN_USE(BAD_REQUEST, "0015"),
    EMAIL_IN_USE(BAD_REQUEST, "0013"),
    LOGIN_CODE_REQUESTS_EXCEEDED(BAD_REQUEST, "0035"),
    ID_DOES_NOT_EXIST(BAD_REQUEST, "0053"),
    NOT_FOUND(BAD_REQUEST, "0404"),
    UNSUFFICIENT_MINUTES_IN_FITTY_PLUS(BAD_REQUEST, "0055"),
    USER_SHOULD_ADD_DEBIT_CARD(BAD_REQUEST, "0056"),
    CUSTOMER_HAVE_TO_REACH_ADMIN(BAD_REQUEST, "0057"),
    USER_HAVE_TO_SELECT_PAYMENT_TYPE(BAD_REQUEST, "0058"),
    UNSUFFICIENT_FUNDS_IN_WALLET(BAD_REQUEST, "0059"),
    USER_HAVE_TO_BUY_FITTY_PLUS(BAD_REQUEST, "0060"),
    USER_HAVE_TO_ADD_VALID_CARD(BAD_REQUEST, "0056"),
    USER_REGISTER_ALREADY_COMPLETED(BAD_REQUEST, "0061"),
    SLIDER_NOT_FOUND(BAD_REQUEST, "0195"),
    EMAIL_NOT_FOUND(BAD_REQUEST, "0198"),
    USER_ALREADY_BANNED(BAD_REQUEST, "0200"),
    USER_ALREADY_ACTIVE(BAD_REQUEST, "0201"),
    THIS_USER_IS_BANNED(BAD_REQUEST, "0203"),
    THIS_USER_IS_DELETED(BAD_REQUEST, "0244"),
    WALLET_NOT_FOUND(BAD_REQUEST, "0205"),
    WALLET_UPPER_LIMIT_OVERLOW(BAD_REQUEST, "0206"),
    SUPPORT_DEMANDS_PER_SIXTY_SECONDS(BAD_REQUEST, "0212"),
    YOU_CAN_SEND_ONE_SMS_PER_MINUTE(BAD_REQUEST, "0213"),
    THERE_IS_NO_ACCESS_CODE(BAD_REQUEST, "0216"),
    INVALID_ACCESS_CODE(BAD_REQUEST, "0217"),
    YOU_CAN_DELETE_UP_TO_75_IMAGES_PER_LOUNGE(BAD_REQUEST, "0222"),
    YOU_CANNOT_DELETE_ALL_IMAGES_OF_A_LOUNGE_ENTITY(BAD_REQUEST, "0223"),
    LOUNGE_ENTITY_CANNOT_HAVE_MORE_THAN_25_IMAGES(BAD_REQUEST, "0117"),
    THIS_IMAGE_IS_NOT_YOURS(BAD_REQUEST, "0224"),
    INVALID_FILE_FORMAT(BAD_REQUEST, "0225"),
    PAYMENT_FOR_TRANING_NOT_FOUND(BAD_REQUEST, "0000"),
    FITTY_PLUS_ID_MUST_NOT_BE_NULL(BAD_REQUEST, "0000"),
    PACKAGE_NOT_FOUND(BAD_REQUEST, "0000"),
    THIS_OPERATION_DOES_NOT_BELONG_TO_THIS_USER(BAD_REQUEST, "0000"),
    INVALID_EXCHANGE_AMOUNT(BAD_REQUEST, "0230"),
    USER_ALREADY_EXITED(BAD_REQUEST, "0233"),
    NOT_PAID_TRAINING_EXISTS(BAD_REQUEST, "0234"),
    YOU_CANNOT_PAY_FITTY_PLUS_TRAINING_WITH_WALLET(BAD_REQUEST, "0235"),
    DUPLICATE_CARD_ALIAS(BAD_REQUEST, "0236"),
    GIVEN_QRCODE_NOT_SAME_WITH_GIVEN_LOUNGE_QRCODE(BAD_REQUEST, "0237"),
    LOUNGE_CLOSED(BAD_REQUEST, "0238"),
    USER_IS_NOT_IN_CORRECT_LOCATION_TO_SCAN_QRCODE(BAD_REQUEST, "0239"),
    LOUNGE_STATUS_NOT_ACTIVE(BAD_REQUEST, "0240"),
    USER_STATUS_NOT_ACTIVE(BAD_REQUEST, "0241"),
    YOU_HAVE_ALREADY_FITTY_PLUS(BAD_REQUEST, "0000"),
    YOU_HAVE_ALREADY_FITTY_PLUS_APPLY(BAD_REQUEST, "0245"),
    YOU_DONT_HAVE_ANY_LOUNGE_PACKAGES(BAD_REQUEST, "0000"),
    QRCODE_NOT_VALID(BAD_REQUEST, "0242"),
    INVALID_IDENTITY_NUMBER(BAD_REQUEST, "0030"),
    INVALID_TAX_OFFICE(BAD_REQUEST, "0104"),
    INVALID_TAX_NUMBER(BAD_REQUEST, "0107"),
    INVALID_COMPANY_TITLE(BAD_REQUEST, "0000"),
    INVALID_ADDRESS(BAD_REQUEST, "0246"),
    INVALID_LOUNGE_MANAGER_CREDENTIALS(BAD_REQUEST, "0000"),
    THIS_LOUNGE_NOT_YOURS(BAD_REQUEST, "0247"),
    IYZICO_PAYMENT_FAIL(BAD_REQUEST, "0248"),
    ALIAS_IS_EMPTY(BAD_REQUEST, "0249"),
    USER_REGISTER_IS_NOT_COMPLETED(BAD_REQUEST, "0250"),


    ;


    private final HttpStatus httpStatus;
    private final String codes;

    ErrorConstants(HttpStatus status, String codes) {
        this.httpStatus = status;
        this.codes = codes;
    }
}
